### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by buildist** [caojiezhang/DAVSR#6]
Seeing the following error when attempting non-distributed training:

```
Traceback (most recent call last):
  File "tools/train.py", line 182, in <module>
    main()
  File "tools/train.py", line 177, in main
    meta=meta,
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python37\lib\site-packages\mmedit\apis\train.py", line 81, in train_model
    meta=meta)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python37\lib\site-packages\mmedit\apis\train.py", line 330, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python37\lib\site-packages\mmcv\runner\iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python37\lib\site-packages\mmcv\runner\iter_based_runner.py", line 61, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python37\lib\site-packages\mmcv\parallel\data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "E:/Code/DAVSR\davsr\models\restorers\davsr_model.py", line 80, in train_step
    outputs = self(**data_batch, test_mode=False)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python37\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python37\lib\site-packages\mmedit\models\restorers\basic_restorer.py", line 77, in forward
    return self.forward_train(lq, gt)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python37\lib\site-packages\mmedit\models\restorers\basic_restorer.py", line 90, in forward_train
    output = self.generator(lq)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:/Code/DAVSR\davsr\models\backbones\sr_backbones\davsr_net.py", line 1003, in forward
    x = self.d(x, FB, FBC, F2B, FBFy, ab[:, i:i + 1, ...], sf)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:/Code/DAVSR\davsr\models\backbones\sr_backbones\davsr_net.py", line 699, in forward
    FR = FBFy + torch.fft.fftn(alpha * x, dim=(2,3,4))              # [1, 3, 100, 256, 256]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by buildist** [comment]
Fixed the error by removing `if not self.training` here (although then I don't have enough VRAM) https://github.com/caojiezhang/DAVSR/blob/main/davsr/models/backbones/sr_backbones/davsr_net.py#L1013
